### ISSUE TITLE
IE: getOffsetParent returns body instead of relative positioned parent element

### ISSUE THREAD

**Issue by jerome8** [sstephenson/prototype#264] opened 2014-09-29 07:48 UTC
Scenario:
I have a simple text input field that uses scriptaculous Ajax.autocomplete inside a parent div with position: relative.

Result:
Resultlist will be positioned wrong in IE9-11 because the calculation of the top value is incorrect.

I traced it down to element.offsetParent which is returning the body instead of the relative positioned parent.
Seems to be a IE bug imo.

Suggestion:
Use element.parentNode loop until a better workaround is found.

**Comment by savetheclocktower** [comment] 2015-05-13 03:01
I've got to say that this is more information than I usually get about layout-related issues, but I can't reproduce this one.

Our test cases already test scenarios where an element is the offset child of a relatively-positioned element, and those all pass in IE 9–11.

But all that happens deep within an absolutely-positioned context, so I tried creating a new test case with this HTML…

```html
<div id="body_relative" style="position: relative;">
  <div id="relative_absolute" style="position: absolute; top: 10px; left: 10px"></div>
</div>
```

…and making this assertion…

```js
assert.equal('body_relative', $('relative_absolute').getOffsetParent().id,
 '#body_relative should be parent of #relative_absolute');
```

…and that passes in IE 10.

I feel really weird about applying a fix for a bug I can't reproduce.

**Comment by savetheclocktower** [comment] 2015-05-13 04:28
Tentatively marking this as a bug just for triage purposes.

**Comment by laurin1** [comment] 2015-05-13 11:54
I'm pretty sure that this was fixed in https://github.com/sstephenson/prototype/issues/156.

**Comment by savetheclocktower** [comment] 2015-05-13 14:59
Yeah, looks that way on closer inspection. Closing.

**Closed by savetheclocktower** 2015-05-13 14:59 UTC
Labels: bug
