### ISSUE TITLE
Allow PUT, DELETE and other HTTP methods on ajax requests

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#208] opened 2014-05-08 14:59 UTC
[previous lighthouse ticket #289](https://prototype.lighthouseapp.com/projects/8886/tickets/289-allow-put-delete-and-other-http-methods-on-ajax-requests) 
by Pablo Bustos

***
"request" function of Ajax.Request class, simulate other verbs (e.g. DELETE, PUT, HEAD, etc) over post.

Why restrict to only get and post requests?

To enable prototype use servlets of my project (that requires DELETE and PUT methods), as a patch, I replaced in that function this line:
```
      this.transport.open(this.method.toUpperCase(), this.url,
        this.options.asynchronous);
```
by this:
```
      this.transport.open(this.options.method.toUpperCase(), this.url,
        this.options.asynchronous);
```
and works perfectly.

**Comment by savetheclocktower** [comment] 2015-05-13 03:31
Duplicate of #280.

**Closed by savetheclocktower** 2015-05-13 03:31 UTC
