### ISSUE TITLE
The method of requests other than GET or POST can never be retrieved by any server application

### ISSUE THREAD

**Issue by jwestbrook** [sstephenson/prototype#207] opened 2014-05-08 14:57 UTC
[previous lighthouse ticket #1245](https://prototype.lighthouseapp.com/projects/8886/tickets/1245-the-method-of-requests-other-than-get-or-post-can-never-be-retrieved-by-any-server-application) 
by Jean-François Morin

***
I am developing a hybrid Web/RESTful application with Spring 3.0.5, whose HiddenHttpMethodFilter class I use to retrieve the original method used in Ajax requests.

On the client side, I use Prototype 1.7 to send Ajax.Requests using the GET, POST, PUT, and DELETE methods. In lines 1505-1512, the original method is replaced by POST but is kept as a request parameter named method. However, this parameter is never appended to any non-GET request, which prevents that block from sending any method other than GET in any Ajax request.

I patched my copy of Prototype (version 1.7) as follows (comments identify the lines I added or changed):
```
var methodAppended = false; // added
if (!['get', 'post'].include(this.method)) {
  params += (params ? '&' : '') + "_method=" + this.method;
  this.method = 'post';
  methodAppended = true; // added
}

if (params && (this.method === 'get' || methodAppended)) { // || methodAppended added
  this.url += (this.url.include('?') ? '&' : '?') + params;
}
```
and everything now works as expected.

**Comment by savetheclocktower** [comment] 2015-05-13 03:34
Duplicate of #280.

**Closed by savetheclocktower** 2015-05-13 03:34 UTC
